version: "3.9"

services:
  mongo-server:
    image: mongo:8.0.0-rc7
    container_name: mongo-server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network

  mongo-client:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-client
    restart: always
    depends_on:
      - mongo-server
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-server
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8081:8081"
    networks:
      - mongodb_network

  app:
    build: .
    container_name: node-app
    restart: always
    ports:
      - 4000:3000
    env_file:
    - .env
    depends_on:
      - mongo-server
    networks:
      - mongodb_network
    volumes:
      - .:/app


volumes:
  mongodb_data: {}

networks:
  mongodb_network:
